spring:
  thymeleaf:
    cache: false
#  datasource:
#    url: jdbc:mysql://
#    username: 
#    password: 

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
